import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { Providers, RecoilProvider } from "./provider"
import Navbar from "@/components/Navbar";
import { Suspense } from "react";
import Loading from "./loading.js"

const inter = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "900", "700"],
});

export const metadata: Metadata = {
  title: "Mind Canvas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <RecoilProvider>
            <Suspense
            fallback={<Loading />}
            >
              <Providers>
                <Navbar />
                {children}
              </Providers>
        </Suspense>
          </RecoilProvider>
      </main>
      <Toaster />
    </body>
    </html >
  );
}
